table 'Training Measures'
	lineageTag: f1091696-8e44-4338-bcf9-9e1e604812c9

	measure 'DIFF SUMs Training Students, All Population' = [SUM Training Students By Nafa, All Population] - [SUM Training Students By Gender, All Population]
		formatString: #,0
		lineageTag: 8b175191-f70c-4e56-ac0f-77c1241c18c3

	measure 'DIFF SUMs Training Students, Arab Population' = [SUM Training Students By Nafa, Arab Population] - [SUM Training Students By Gender, Arab Population]
		formatString: #,0
		lineageTag: a8070049-bde6-4a5c-8a27-8f191451919f

	partition 'Training Measures' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

