DEFINE
	MEASURE 'Core Measures'[SUM Higher Ed] = SUM('Fact Higher Education'[Value])
	MEASURE 'Core Measures'[SUM Students by Institution] = SUM('Fact Lamas Students by Institution'[Value])
	MEASURE 'Core Measures'[SUM Students by Gender] = SUM('Fact Lamas Students by Gender'[Value])
	MEASURE 'Core Measures'[SUM Graduates by Nafa] = SUM('Fact Lamas Graduates by Nafa'[Value])
	MEASURE 'Key Metric'[Key Metric] = VAR RESULT =
		SWITCH(
			SELECTEDVALUE('Key Metric'[Metric]),
			"SUM Higher Ed", [SUM Higher Ed],
			"SUM Students by Institution", [SUM Students by Institution],
			"SUM Students by Gender", [SUM Students by Gender],
			"SUM Graduates by Nafa", [SUM Graduates by Nafa]
		)
		RETURN
			ROUNDUP(
				result,
				0
			)
	MEASURE 'Key Metric'[Key Metric, Arab Population] = CALCULATE(
			[Key Metric],
			FILTER(
				ALL(Population),
				Population[Population] = "Arab"
			)
		)
	MEASURE 'Key Metric'[Key Metric, Arab Population, All Technological Subjects] = CALCULATE(
			[Key Metric, Arab Population],
			FILTER(
				ALL(Subject),
				Subject[תחום] <> "לא הייטק"
			)
		)
	MEASURE 'Key Metric'[Key Metric, Arab Population, All Subjects] = CALCULATE(
			[Key Metric, Arab Population],
			ALL(Subject)
		)
	MEASURE 'Key Metric'[Key Metric, Arab % Technological Subjects of All Subjects] = DIVIDE(
			[Key Metric, Arab Population, All Technological Subjects],
			[Key Metric, Arab Population, All Subjects]
		)

EVALUATE
	SUMMARIZECOLUMNS(
		"SUM Higher Ed", 'Core Measures'[SUM Higher Ed],
		"SUM Students by Institution", 'Core Measures'[SUM Students by Institution],
		"SUM Students by Gender", 'Core Measures'[SUM Students by Gender],
		"SUM Graduates by Nafa", 'Core Measures'[SUM Graduates by Nafa],
		"Key Metric", 'Key Metric'[Key Metric],
		"Key Metric, Arab Population", 'Key Metric'[Key Metric, Arab Population],
		"Key Metric, Arab Population, All Technological Subjects", 'Key Metric'[Key Metric, Arab Population, All Technological Subjects],
		"Key Metric, Arab Population, All Subjects", 'Key Metric'[Key Metric, Arab Population, All Subjects],
		"Key Metric, Arab % Technological Subjects of All Subjects", 'Key Metric'[Key Metric, Arab % Technological Subjects of All Subjects]
	)